name: Backend Sonar Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build Project
        run: mvn clean install

      - name: Sonar Scan
        run: mvn sonar:sonar \
          -Dsonar.projectKey=Rathi9641_skills-backend \
          -Dsonar.organization=rathi9641 \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
